# ports: HOST:CONTAINER
version: '3.8'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: ${OV_SERVICE_NAME}
    ports:
      - ${OV_PORT}:1194/udp
    restart: unless-stopped
    volumes:
      - OV_VOLUME:/etc/openvpn

volumes:
  OV_VOLUME:
    external:
      name: ${OV_VOLUME}
